### ISSUE TITLE
v1.2.1 make 失败

### ISSUE THREAD

**Issue by caijian76** [filecoin-project/venus-messager#159]
go: github.com/ipfs-force-community/venus-gateway@v1.1.2-0.20210731031356-770f19abfbcb (replaced by /Users/lijunlong/code/venus-gateway): reading /Users/lijunlong/code/venus-gateway/go.mod: open /Users/lijunlong/code/venus-gateway/go.mod: no such file or directory

**Comment by shmilytsui** [comment]
who is lijunlong?
I have a question about v1.2.1:

root@test-135:/opt/src/git-src/venus-messager# make
rm -rf venus-messager
go build -ldflags="-X=github.com/filecoin-project/venus-messager/version.GitCommit=579a373" -o venus-messager .
go: github.com/ipfs-force-community/venus-gateway@v1.1.2-0.20210731031356-770f19abfbcb (replaced by /Users/lijunlong/code/venus-gateway): reading /Users/lijunlong/code/venus-gateway/go.mod: open /Users/lijunlong/code/venus-gateway/go.mod: no such file or directory
go: github.com/ipfs-force-community/venus-gateway@v1.1.2-0.20210731031356-770f19abfbcb (replaced by /Users/lijunlong/code/venus-gateway): reading /Users/lijunlong/code/venus-gateway/go.mod: open /Users/lijunlong/code/venus-gateway/go.mod: no such file or directory
make: *** [Makefile:12: build] Error 1

**Comment by diwufeiwen** [comment]
> who is lijunlong? I have a question about v1.2.1:
> 
> root@test-135:/opt/src/git-src/venus-messager# make rm -rf venus-messager go build -ldflags="-X=github.com/filecoin-project/venus-messager/version.GitCommit=579a373" -o venus-messager . go: github.com/ipfs-force-community/venus-gateway@v1.1.2-0.20210731031356-770f19abfbcb (replaced by /Users/lijunlong/code/venus-gateway): reading /Users/lijunlong/code/venus-gateway/go.mod: open /Users/lijunlong/code/venus-gateway/go.mod: no such file or directory go: github.com/ipfs-force-community/venus-gateway@v1.1.2-0.20210731031356-770f19abfbcb (replaced by /Users/lijunlong/code/venus-gateway): reading /Users/lijunlong/code/venus-gateway/go.mod: open /Users/lijunlong/code/venus-gateway/go.mod: no such file or directory make: *** [Makefile:12: build] Error 1

The master branch has been fixed, thanks for your feedback
