### ISSUE TITLE
some wrong about v1.2.1

### ISSUE THREAD

**Issue by shmilytsui** [filecoin-project/venus-messager#164]
like venus-auth, there's some wrong about venus-message v1.2.1
when I input make, there's Wrong:

go: github.com/ipfs-force-community/venus-gateway@v1.1.2-0.20210731031356-770f19abfbcb (replaced by /Users/lijunlong/code/venus-gateway): reading /Users/lijunlong/code/venus-gateway/go.mod: open /Users/lijunlong/code/venus-gateway/go.mod: no such file or directory
make: *** [Makefile:12: build] Error 1

～～Hi, Dear lijunlong, I see you again ……~

**Comment by simlecode** [comment]
please use v1.2.2-rc1
